Initial support for TOPO
introlab/t-top pull request #56
Opened 2022-10-25 15:57 UTC by philippewarren

Also, can now build with catkin_tools' `catkin build`.

2022-10-25 17:28 UTC, mamaheux requested changes

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +gi.require_version("Gst", "1.0")
Can you use ' instead of " to be consistent with other python node?

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +class VideoStreamConfig:
Rename to VideoStreamConfiguration

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +    class VideoStreamParams(TypedDict):
Rename to VideoStreamParameters

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +class AudioStreamConfig:
Rename to AudioStreamConfiguration

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +    class AudioStreamParams(TypedDict):
Rename to AudioStreamParameters

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +        )
Why do use cast?

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +
Why do you add language code?

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +    nv_hw_enc: Optional[str]
Use full name

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +    enc: str
Use full name

2022-10-25 17:28 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +    H264 = ("h264", "x264enc", "nvv4l2h264enc", "h264parse")
I didn't know you can create a custom enum class to add fields!

2022-10-25 18:45 UTC, philippewarren commented on ros/utils/recorders/scripts/video_recorder_node.py
> +        )
`rospy.get_param` is weirdly type and the static type checker doesn't know it should return a str.

2022-10-25 18:46 UTC, philippewarren commented on ros/utils/recorders/scripts/video_recorder_node.py
> +
This allows to differentiate the streams in the resulting mkv container during playback using VLC or the GNOME video player. Technically, it means that you need to remember an arbitrary language code as an alternative to remembering the stream's ordering.
Would the ordering be sufficient?

2022-10-26 21:07 UTC, mamaheux approved these changes

2022-10-26 21:13 UTC, mamaheux commented on ros/utils/recorders/scripts/video_recorder_node.py
> +
Yes

2022-10-26 21:13 UTC, merged