Force little endian in the perception logger database.
introlab/t-top pull request #63
Opened 2022-11-08 15:10 UTC by mamaheux

2022-11-08 15:16 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static_assert(AlwaysFalse<T>::value, "Not supported type");
The static_assert is always trigger with std::false_type directly.

2022-11-08 15:16 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/PerceptionLogger.h
> +    Position(double x, double y, double z) : x(x), y(y), z(z) {}
Added because of the inheritance.

2022-11-08 16:55 UTC, philippewarren requested changes

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +        uint8_t bytes[4];
This could be `std::array<std::byte, N>` too, if we choose to go with that for the return type.

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/PerceptionLogger.h
> +    Position(double x, double y, double z) : x(x), y(y), z(z) {}
See my comment on is_value_type<T>

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    size_t m_size;
std::span would be nice here, too bad we don't have C++20 yet!

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    void* m_data;
std::bytes* instead?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    const void* data() const { return m_data; }
std::bytes*?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(T&&) = delete;  // Disallow temporaries
Why? Because we are non-owning?
Couldn't we move in that case?
No supporting this means that `serialize(23)` would fail, and there is no owning issue here.

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(std::vector<T>&&) = delete;  // Disallow temporaries
Couldn't we move?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(std::vector<T>&&) = delete;  // Disallow temporaries
Couldn't we move?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/PerceptionLogger.h
> +}
If we choose to go the `std::array<std::bytes>` route, these would all just return a concatenated array of std::bytes.

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/PerceptionLogger.h
> +    ImagePosition center;
I wasn't sure if we were going Canadian or United-Statesian on this one, it might appear in other places too.

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/PerceptionLogger.h
>  struct BoundingBox
We could add the packed attribute so that we don't forget it if we ever put these in blobs. Also, it's already half-packed because of the center member anyway.

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/src/perception_logger/BinarySerialization.cpp
> +Bytes::Bytes(size_t size) : m_owned(true), m_data(malloc(size)), m_size(size) {}
Use new std::bytes[] instead of malloc?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/src/perception_logger/BinarySerialization.cpp
> +        free(m_data);
Use delete[] instead of free?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/src/perception_logger/BinarySerialization.cpp
> +}
Is self-move handled?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/src/perception_logger/BinarySerialization.cpp
> +}
Is self-mode handled?

2022-11-08 16:55 UTC, philippewarren commented on ros/utils/recorders/src/perception_logger/sqlite/SQLiteVideoAnalysisLogger.cpp
>      insert.bind(6, analysis.boundingBox.height);
Is the serialization done by the sql library here?

2022-11-08 17:24 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +};
Good idea!

2022-11-08 17:26 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/PerceptionLogger.h
> +    ImagePosition center;
In T-Top, United-Statesian spelling is udes.

2022-11-08 17:31 UTC, mamaheux commented on ros/utils/recorders/src/perception_logger/sqlite/SQLiteVideoAnalysisLogger.cpp
>      insert.bind(6, analysis.boundingBox.height);
Yes

2022-11-08 17:39 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    size_t m_size;
Yes!

2022-11-08 17:39 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    void* m_data;
Good idea!

2022-11-08 17:44 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(T&&) = delete;  // Disallow temporaries
Yes, I remove the support temporaries because we are non_owning on little endian computers.

serialize(23) is fine because the constant 23 have a fixed address in the program, but serialize(vector<int>{23}) will cause a seg fault later on little endian computers.

I prefer preventing seg fault and making the interface less usable.

2022-11-08 17:45 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(std::vector<T>&&) = delete;  // Disallow temporaries
See the other comment

2022-11-08 17:46 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(std::vector<T>&&) = delete;  // Disallow temporaries
See the other comment

2022-11-08 17:47 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(T&&) = delete;  // Disallow temporaries
We cannot move the output type is Bytes.

2022-11-08 17:48 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(T&&) = delete;  // Disallow temporaries
A solution to this issue is to always copy the data, so Bytes will always own the data.

2022-11-08 19:00 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +        if (isLittleEndian())
if constexpr with else

2022-11-08 19:01 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(T&&) = delete;  // Disallow temporaries
Ah, yep, I just realized that the owning state depends of the endianness.
We should probably not always copy the data.
Maybe we could use `std::enable_if` to have the && overload exist if the data is small enough to be copied?
Or we create a serialize_always_copy version for rvalues?

2022-11-08 19:01 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +        if (isLittleEndian())
if constexpr with else

2022-11-08 19:05 UTC, philippewarren commented on ros/utils/recorders/test/perception_logger/BinarySerializationTests.h
> +    if (isLittleEndian())
if constexpr?

2022-11-08 19:05 UTC, philippewarren commented on ros/utils/recorders/test/perception_logger/BinarySerializationTests.h
> +    if (isLittleEndian())
if constexpr?

2022-11-08 19:39 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
The class is needed because of the specialization of vector<T> that doesn't work if it is not in a class.

2022-11-08 19:58 UTC, philippewarren commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
This suprised me. I tried it, and it seems to work?
https://godbolt.org/z/86GcdbGx6

2022-11-08 20:00 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
I had this issue in another project. I will make the changes.

2022-11-08 20:10 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
If you add `Bytes serializeToBytes(T&&) = delete;`, your example won't compile.

2022-11-08 20:16 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
So, I will leave the class here.
Also, the serialize(vector<t>) is an overload and not a specialization.

2022-11-08 20:27 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +    static Bytes serialize(T&&) = delete;  // Disallow temporaries
I will rename the method serializeNoCopy and let the next person add the serialize that always copy.

2022-11-09 00:57 UTC, mamaheux commented on ros/utils/recorders/src/perception_logger/BinarySerialization.cpp
> +    }
Is it possible to perform seft-move with the constructor?

2022-11-09 03:25 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
Finally, I fixed the issue by providing another overloads that take a non-const reference.
See https://godbolt.org/z/c4r1dhscn

2022-11-09 16:41 UTC, philippewarren requested changes

2022-11-09 17:43 UTC, mamaheux commented on ros/utils/recorders/include/perception_logger/BinarySerialization.h
> +{
I prefer the const_cast.

2022-11-09 17:44 UTC, mamaheux commented on ros/utils/recorders/src/perception_logger/BinarySerialization.cpp
> +    }
I will keep the check here to be safe.

2022-11-09 18:26 UTC, philippewarren approved these changes

2022-11-09 18:27 UTC, merged